gwSites/gwSites/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gwSites.views.home', name='home'),
    # url(r'^gwSites/', include('gwSites.foo.urls')),
    url(r'^/?$', 'gwSites.influBuild.views.home', name='home'),
	url(r'^contact/$','gwSites.influBuild.views.contact', name='contact'),
    
    #this url is only to be used  for initialisation purposes, thus, it's disabeld
	url(r'^init/?$','gwSites.influBuild.views.initDb'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

gwSites/gwSites/influBuild/models.py
from django.db import models

# Create your models here.

class Building(models.Model):
	name = models.CharField(max_length=30)
	shortName = models.CharField(max_length=7,primary_key=True)
	cost = models.IntegerField(default=200)
	timeToBuild = models.IntegerField(default=24)
	isRepetable = models.BooleanField(default=True)
	family = models.CharField(max_length=30)
	parent = models.ForeignKey('self', blank = True, null = True, related_name = '%(app_label)s_%(class)s_descendant')
	otherDep = models.ForeignKey('self', blank = True, null = True, related_name = '%(app_label)s_%(class)s_otherDesc')
	completeDescr = models.CharField(max_length=200)
	
	def __unicode__(self):
		return u'%s' % (self.shortName)

gwSites/gwSites/influBuild/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	sender = forms.EmailField()
	message = forms.CharField(widget=forms.Textarea)
	

gwSites/gwSites/influBuild/views.py
from gwSites.influBuild.initDb import initDatabase
from gwSites.influBuild.models import Building
from gwSites.influBuild.forms import ContactForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.mail import send_mail
#from django.utils.translation import ugettext_lazy as _
# Create your views here.

def initDb(request):
	initDatabase()
	return HttpResponseRedirect('/')
	
def home(request):
	allB=Building.objects.order_by('shortName')#['Pol','Art','Eco','Arc']
	form = ContactForm()
	return render(request,'influMainPage.html',
				 {'listFam':{'Architecture':allB.filter(family='Arc'),'Politics':allB.filter(family='Pol'),'Art Of War':allB.filter(family='Art'),'Economy':allB.filter(family='Eco')},
				 'form':form})
							 
def contact(request):
	if request.POST:
		form = ContactForm(request.POST)
		if form.is_valid():
			send_mail(form.cleaned_data['subject'],form.cleaned_data['message'],form.cleaned_data['sender'],["gestion@cladiere.eu"])
			#if request.is_ajax():
				#print("a")
				#return render (request, 'form.html', {'form' : form })
		return render (request, 'form.html', {'form' : form })
	return redirect('home')		

templates/form.html
{% load i18n %}
<div id="contactDiv">
	<h3> {% trans "Contact Form" %}</h3>
	<form action="{% url 'contact' %}" method="post" id="contactForm">
		<div id="formInnerDiv">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="fieldWrapper">
				{{ form.subject.errors }}
				<label for="id_subject"> {% trans "Subject" %} :</label>
				{{ form.subject}}
			</div>
			<div class="fieldWrapper">
				{{ form.sender.errors }}
				<label for="id_sender"> {% trans "Sender" %} :</label>
				{{ form.sender }}
			</div>
			<div class="fieldWrapper">
				{{ form.message.errors }}
				<label for="id_message"> {% trans "Message" %} :</label>
				<br/>
				{{ form.message }}
			</div>
			<input type='submit' value='{% trans "Send" %}' id='sendbtn'/>
		</div>
		<div id="thanksDiv">
			<div id="innerThanks">
				{% trans "Thanks !" %}
			</div>
		</div>
	</form>
</div>

templates/influMainPage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr-fr" xml:lang="fr-fr" >
{% load i18n %}
{% load compressed %}
<head>
	<title>{% trans "Elaborate your guild builds" %}</title>
	<link type="text/css"  href="{{ STATIC_URL }}css/blitzer/jquery-ui-1.8.20.custom.css" rel="stylesheet"/>
	{% compressed_css 'influCSS' %}
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.20.custom.min.js"></script>
	{% comment %}
	<link type="text/css"  href="{{ STATIC_URL }}css/influBuild.css" rel="stylesheet"/>
	<script type="text/javascript" src="{{ STATIC_URL }}js/influBuild.js"></script>
	{% endcomment %}
	{% compressed_js 'influJS' %}
	<script type="text/javascript">
		var listBuilds={{% for fam, builds in listFam.items %}
			 '{{ fam|slice:":3" }}' : { 
			{% for build in builds %}	 '{{ build.shortName }}' : new building('{% trans build.name %}','{{build.parent|default_if_none:""}}', '{{build.otherDep|default_if_none:""}}', {{build.cost}}, {{build.timeToBuild}}, [{% for indirectChilds in build.influbuild_building_otherDesc.values %} '{{indirectChilds.shortName}}',{% endfor %}],"{% trans build.completeDescr %}"),
			{% endfor %}	},{% endfor %}
		};
		var oNs = { {% for fam, builds in listFam.items %}'{{fam|slice:":3"}}':'{{fam|slice:"2:3"}}',{% endfor %} };
		var iNs = { {% for fam, builds in listFam.items %}'{{fam|slice:"2:3"}}':'{{fam|slice:":3"}}',{% endfor %} };
		
	</script>
</head>
{% spaceless %}<body>

<div id="buttonDiv">
	<img class="imgBtn" id="leftImg" src="{{ STATIC_URL }}img/withColors.png" />
	<img class="imgBtn" id="rightImg" src="{{ STATIC_URL }}img/withColors.png" />
	<input type="button" value="{% trans "Reset and enter Construction Mode"%}" id="constrMod" />
	<input type="button" value="{% trans "Exit Construction Mode"%}" id="exitCM" />
	<input type="button" value="{% trans "Get a link to the current status"%}" id="linkOut"/>
	<input type="button" value="{% trans "FAQ"%}" id="showFAQ"/>
	<br/>
	<input type="button" value="{% trans "Reset"%}" id="reset"/>
	<input type="button" value="{% trans "Output build order"%}" id="printOut"/>
	<input type="button" value="{% trans "Contact"%}" id="contact"/>
</div>
<div id="influBuildList">
	<div id="timeLine" class="line fillBy5"><div>{% trans "Time" %}</div></div>
	<div id="buildList0" class="line"><div>{% trans "Basic build Line" %}</div></div>
	<div id="buildList1" class="line"><div>{% trans "Workshop build line" %}</div></div>
	<div id="buildList2" class="line"><div>{% trans "Asura build line" %}</div></div>
	<div id="costPerDay" class="line fillBy5" ><div>{% trans "Influence spent for the current day" %}</div></div>
	<div id="totalCost" class="line fillBy5" ><div>{% trans "Total Cost up to the current day" %}</div></div>
</div>
<div id="buildingContent">
	<div id="bCaccordion">
	{% for fam, builds in listFam.items reversed%}
		<h3 class="acc_header" id='h3{{fam|slice:":3"}}'><a href="#">{% trans fam %}</a></h3>
		<div id='{{fam|slice:":3"}}' class="family">
		{% for build in builds %}
			{# levels all have a shortName 4 char long #}
			{% if build.shortName|length == 4 %}
				{% if not forloop.first %}
					</div>
				{% endif %}
				<div class="colFam">
			{% endif %}
			<div id='{{ build.shortName }}' class="cellFam {% if build.parent != None %}noSelect{% endif %} {%if build.isRepetable %}canRepeat{% endif %} unselectable='on'">{% trans build.name %}</div>
		{% endfor %}
			</div>
		</div>
	{% endfor %}
	</div>
</div>

<div id="legend">
	<div class="title">{% trans "Legend" %}:</div>
	<div class="exCol">
		<div class="exCF exBg">{% trans "You can place me" %}</div>
		<div class="exCF exBg exUse">{% trans "Already built, can't do it again" %}</div>
		<div class="exCF exBg exNS">{% trans "You can't use me yet" %}</div>
		<div class="exCF exBg exMD">{% trans "I might be deleted" %}</div>
	</div>
	<div class="exCol">
		<div class="exCF exBor">{% trans "I'm a permanent building" %}</div>
		<div class="exCF exBor canRepeat">{% trans "I'm not" %}</div>
		<div class="exCF exBor preReq">{% trans "You need me for that thing" %}</div>
	</div>
</div>
<div id="footer">
© 2012 ArenaNet, Inc. All rights reserved. NCsoft, the interlocking NC logo, ArenaNet, Guild Wars, Guild Wars Factions, Guild Wars Nightfall, Guild Wars: Eye of the North, Guild Wars 2, and all associated logos and designs are trademarks or registered trademarks of NCsoft Corporation. All other trademarks are the property of their respective owners.
<br/>
{% trans "Website made by La Folie (aka LFT). Anyone is free to use it." %} 
</div>
<div id="faqDialog">
	<div id="accorFaq">
		<h3><a href="#">{% trans "What's the use of this website" %}?</a></h3>
		<div>
			{% trans "It provides a simulation of the building process in Guild Wars 2" %}. <br/> 
			{% trans "It gives players a way to quickly estimate what is the best thing for them to build. And what will they need to spend in order to do so" %}.
		</div>
		<h3><a href="#">{% trans "Why does nothing works" %}?</a></h3>
		<div>
			{% trans "Probably because your browser does not allow javascript or is to old (it's tested on firefox and chrome only)"%}.
		</div>

		<h3><a href="#">{% trans "How does that work" %}?</a></h3>
		<div>
			{% trans "There are two kind of buildings"%}, <span class="exFAQ">{% trans "permanent"%}</span>{% trans "and"%}<span class="exRe">{% trans "temporary"%}</span>.<br/>
			{% trans "The difference between the two is quite easy to get. Once built, the permanent will be there until deletion. The temporary will be there once and will be available again when the need arise" %}.<br/>
			{% trans "A building that you can place has a black background. A permanent and constructed building will be grey" %}.<br/>
			{% trans "If you hover over a building with a blue background, you'll see what are the"%} <span class="exPReq">{% trans "prerequisite"%}</span>.<br/>
			{% trans "Any building on the build list can be deleted through the click of the red cross in the top right corner" %}.
		</div>
		<h3><a href="#">{% trans "What's 'Construction mode'" %}?</a></h3>
		<div>
			{% trans "This mode allows you to put some permanent batiment in a 'already built' mode. This way, you won't have to place them on the list to access their children" %}.<br/> 
			{% trans "In construction mode, you don't need to build buildings one at a time. You can click on all the permanent buildings and all their ancestors are going to be build as well" %}. <br/>
			{% trans "In construction mode, you can only build permanent buildings" %}.
		</div>

		<h3><a href="#">{% trans "What's represented through"%} "{% trans "Output build order" %}"?</a></h3>
		<div>
			{% trans "It's the order you'll have to put the building in if you only have one list to put all the buildings" %}.
		</div>
		<h3><a href="#">{% trans "How does the deletion work" %}?</a></h3>
		<div>
			{% trans "It shows you the elements that are going to be deleted if you click on the cross. To get that it proceeds to a simulation of the following" %}:
			<ul>
				<li>{% trans "It suppress the building you have your pointer over" %}. </li>
				<li>{% trans "And then it removes all it's children if it has some" %}.</li>
				<li>{% trans "After that it'll move all the element to the left to close the gaps and check for all the possible new mistakes (e.g. children built before their parent)" %}.</li>
				<li>{% trans "And it'll do that until it's good" %}.</li>
			</ul>
		</div>
		<h3><a href="#">{% trans "What about the building speeding process" %}?</a></h3>
		<div>
			{% trans "Yet, I have no idea whatsoever on the way it works in game" %}.
		</div>
		<h3><a href="#">{% trans "Does this site breaks NDA" %}?</a></h3>
		<div>
			{% trans "Short answer: No" %}.<br/>
			{% trans "The value for levels 4 and 5 are only a guess and set to : 7500 influence / 5 days and 10000 influence / 7 days" %}.<br/>
			{% trans "All the datas are based on those found in the game beta and on the" %} <a href='http://wiki.guildwars2.com/wiki/Main_Page'>{% trans "Guild Wars 2 Wiki" %}</a>.

		</div>
		<h3><a href="#">{% trans "I have some ideas/remarks/bugs or I'm not happy with some behavior. What do I do" %}?</a></h3>
		<div>
			{% trans "Just use the contact form, it's here for that" %}.<br/> 
			{% trans " Also note that I'm doing that for free, on my spare time. Hence I might not answer (or correct the bugs) quickly" %}.
		</div>
		<h3><a href="#">{% trans "What are you using to run this website" %}?</a></h3>
		<div>
			{% trans "It's powered by"%} <a href="http://httpd.apache.org/">apache</a>, <a href='https://www.djangoproject.com/'>django</a>, <a href='http://jquery.com/'>jQuery</a> {% trans "and"%} <a href='http://jqueryui.com/'>jQuery-UI</a>.
		</div>
		<h3><a href="#">{% trans "What languages are available" %}?</a></h3>
		<div>
			{% trans "So far, only english and french. And that rely on your browser's locale"%}.
			{% trans "You're welcome if you want to provide another language translation. I can provide easily a list of sentence to be translated"%}.
		</div>
	</div>
</div>

<div id="buildTooltip">
	<div id="innerTooltip">
		<div id="innerTooltipImg" ></div>
		<span id="innerTooltipText"></span>
	</div>
</div>
{% include "form.html" %}

<div id='widthTester'></div>
</body>{% endspaceless %}
</html>